# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-14 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=256)),
                ('current_patient_id', models.IntegerField(blank=True, null=True)),
                ('kiosk_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('home_phone', models.CharField(blank=True, max_length=14)),
                ('cell_phone', models.CharField(blank=True, max_length=14)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('employer_city', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.CharField(blank=True, max_length=200)),
                ('employer_state', models.CharField(blank=True, max_length=200)),
                ('employer_zip_code', models.CharField(blank=True, max_length=200)),
                ('primary_care_physician', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('social_security_number', models.CharField(blank=True, max_length=20)),
                ('responsible_party_name', models.CharField(blank=True, max_length=200)),
                ('responsible_party_phone', models.CharField(blank=True, max_length=14)),
                ('responsible_party_relation', models.CharField(blank=True, max_length=200)),
                ('responsible_party_email', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Doctor')),
            ],
        ),
    ]
