# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('exam_room', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(max_length=20, null=True)),
                ('deleted_flag', models.BooleanField()),
                ('scheduled_time', models.DateTimeField()),
                ('in_room_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='kiosk_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='office',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Office'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Patient'),
        ),
    ]
