# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-15 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20170815_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
    ]
