# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_auto_20170816_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='in_room_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
